Update Constants.cs
Assets\Scripts\Shared\Constants.cs(26,11): error CS0103: The name 'AppDomain' does not exist in the current context
FIXED THIS. :)